### ISSUE TITLE
Getting App crashed: in this line MessengerKit.bundle

### ISSUE THREAD

**Issue by Super-SkilApp** [steve228uk/MessengerKit#44] opened 2019-06-21 09:40 UTC
Getting App crashed:
in this line MessengerKit.bundle

private func loadFromDefaultNib() {
        let view = UINib(nibName: "MSGMessengerView", bundle: MessengerKit.bundle)
            .instantiate(withOwner: self, options: nil).first as? MSGMessengerView
        
        view?.frame = CGRect.zero
        view?.backgroundView.backgroundColor = style.inputViewBackgroundColor
        view?.add(collectionView)
        view?.add(messageInputView)
        
        self.view = view
   }

(https://user-images.githubusercontent.com/51957694/59913816-91fe0780-9436-11e9-822e-e761b1dc6418.png)

**Comment by sjoness** [comment] 2020-06-27 23:30
Closing as I cannot reproduce. Will re-address this if it comes up again

**Closed by sjoness** 2020-06-27 23:30 UTC
